package schema

import (
	"errors"
	"strings"
	"testing"
)

func TestCreatePostgresTableRendersNeutralIdentity(t *testing.T) {
	frontier := int64(50)
	table := Table{
		Schema: "archive",
		Name:   "accounts",
		Identity: &Identity{
			Column:     "id",
			Generation: IdentityByDefault,
			Frontier:   &frontier,
		},
		Columns: []Column{
			{
				Name:               "id",
				Type:               "bigint",
				Nullable:           true,
				PrimaryKey:         true,
				PrimaryKeyPosition: 1,
			},
			{Name: "label", Type: "text", Nullable: false},
		},
	}

	got, err := CreateTable(Postgres, table)
	if err != nil {
		t.Fatal(err)
	}
	want := `CREATE TABLE "archive"."accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY, "label" TEXT NOT NULL, PRIMARY KEY ("id"));`
	if got != want {
		t.Fatalf("PostgreSQL identity DDL:\n got: %s\nwant: %s", got, want)
	}

	integer := table
	integer.Columns = append([]Column(nil), table.Columns...)
	integer.Columns[0].Type = "integer"
	got, err = CreateTable(Postgres, integer)
	if err != nil {
		t.Fatalf("render integer PostgreSQL identity: %v", err)
	}
	want = `CREATE TABLE "archive"."accounts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, "label" TEXT NOT NULL, PRIMARY KEY ("id"));`
	if got != want {
		t.Fatalf("PostgreSQL integer identity DDL:\n got: %s\nwant: %s", got, want)
	}
}

func TestCreatePostgresTableRejectsInvalidIdentityShapes(t *testing.T) {
	frontier, negative := int64(50), int64(-1)
	base := Table{
		Name: "accounts",
		Identity: &Identity{
			Column:     "id",
			Generation: IdentityByDefault,
			Frontier:   &frontier,
		},
		Columns: []Column{
			{
				Name:               "id",
				Type:               "bigint",
				PrimaryKey:         true,
				PrimaryKeyPosition: 1,
			},
			{Name: "label", Type: "text"},
		},
	}
	tests := []struct {
		name   string
		mutate func(*Table)
	}{
		{
			name: "unsupported generation",
			mutate: func(table *Table) {
				table.Identity.Generation = "always"
			},
		},
		{
			name: "negative frontier",
			mutate: func(table *Table) {
				table.Identity.Frontier = &negative
			},
		},
		{
			name: "missing column",
			mutate: func(table *Table) {
				table.Identity.Column = "missing"
			},
		},
		{
			name: "composite primary key",
			mutate: func(table *Table) {
				table.Columns[1].PrimaryKey = true
				table.Columns[1].PrimaryKeyPosition = 2
			},
		},
		{
			name: "non-integer identity",
			mutate: func(table *Table) {
				table.Columns[0].Type = "text"
			},
		},
		{
			name: "identity default",
			mutate: func(table *Table) {
				table.Columns[0].Default = &Expression{
					sql:     "1",
					kind:    expressionNumber,
					literal: "1",
				}
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			table := base
			table.Columns = append([]Column(nil), base.Columns...)
			identity := *base.Identity
			table.Identity = &identity
			test.mutate(&table)
			_, err := CreateTable(Postgres, table)
			var policy *PolicyError
			if !errors.As(err, &policy) {
				t.Fatalf("error = %v, want PolicyError", err)
			}
			if policy.Operation != "render PostgreSQL identity" ||
				!strings.Contains(err.Error(), "accounts") {
				t.Fatalf("unexpected identity policy error: %v", err)
			}
		})
	}
}
