package schema

import (
	"errors"
	"strings"
	"testing"
)

func TestCreatePostgresTableRendersSQLiteAutoIncrementIdentity(t *testing.T) {
	frontier := int64(50)
	table := Table{
		Schema:              "archive",
		Name:                "accounts",
		AutoIncrementColumn: "id",
		SQLiteSequence:      &frontier,
		Columns: []Column{
			{
				Name:               "id",
				Type:               "bigint",
				Nullable:           true,
				PrimaryKey:         true,
				PrimaryKeyPosition: 1,
			},
			{Name: "label", Type: "text", Nullable: false},
		},
	}

	got, err := CreateTable(Postgres, table)
	if err != nil {
		t.Fatal(err)
	}
	want := `CREATE TABLE "archive"."accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY, "label" TEXT NOT NULL, PRIMARY KEY ("id"));`
	if got != want {
		t.Fatalf("PostgreSQL identity DDL:\n got: %s\nwant: %s", got, want)
	}
}

func TestCreatePostgresTableRejectsInvalidSQLiteIdentityShapes(t *testing.T) {
	frontier, negative := int64(50), int64(-1)
	base := Table{
		Name:                "accounts",
		AutoIncrementColumn: "id",
		SQLiteSequence:      &frontier,
		Columns: []Column{
			{
				Name:               "id",
				Type:               "bigint",
				PrimaryKey:         true,
				PrimaryKeyPosition: 1,
			},
			{Name: "label", Type: "text"},
		},
	}
	tests := []struct {
		name   string
		mutate func(*Table)
	}{
		{
			name: "sequence without identity",
			mutate: func(table *Table) {
				table.AutoIncrementColumn = ""
			},
		},
		{
			name: "negative sequence",
			mutate: func(table *Table) {
				table.SQLiteSequence = &negative
			},
		},
		{
			name: "missing column",
			mutate: func(table *Table) {
				table.AutoIncrementColumn = "missing"
			},
		},
		{
			name: "composite primary key",
			mutate: func(table *Table) {
				table.Columns[1].PrimaryKey = true
				table.Columns[1].PrimaryKeyPosition = 2
			},
		},
		{
			name: "non-bigint identity",
			mutate: func(table *Table) {
				table.Columns[0].Type = "integer"
			},
		},
		{
			name: "identity default",
			mutate: func(table *Table) {
				table.Columns[0].Default = &Expression{
					sql:     "1",
					kind:    expressionNumber,
					literal: "1",
				}
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			table := base
			table.Columns = append([]Column(nil), base.Columns...)
			test.mutate(&table)
			_, err := CreateTable(Postgres, table)
			var policy *PolicyError
			if !errors.As(err, &policy) {
				t.Fatalf("error = %v, want PolicyError", err)
			}
			if policy.Operation != "map SQLite AUTOINCREMENT" ||
				!strings.Contains(err.Error(), "accounts") {
				t.Fatalf("unexpected identity policy error: %v", err)
			}
		})
	}
}
